/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kms;

import org.junit.Test;
import static org.junit.Assert.*;

/*
public class AppTest {
    @Test public void testAppHasAGreeting() {
        WvsCenter classUnderTest = new WvsCenter();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
*/